model_params:
  name: 'VanillaVAEPro'
  in_channels: 3
  latent_dim: 128


data_params:
  data_path: "/home/kuavg/research/carlatools/doc/AutoDataSaverExample/results"
  train_batch_size: 64
  val_batch_size:  64
  crop_size: 192
  patch_size: 192
  num_workers: 10
  image_folder: "bev"
  random_crop_chance: 0.3

exp_params:
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95
  kld_weight: 0.00025
  manual_seed: 42

trainer_params:
  gpus: [0, 1]
  max_epochs: 100

logging_params:
  save_dir: "logs/"
  name: "VanillaVAEPro"
  
